SELECT * FROM dba_data_files;

CREATE TABLESPACE cdcdemo DATAFILE '/datum/oradata/cont/cdcdemo01.dbf' SIZE 1G AUTOEXTEND ON NEXT 64M MAXSIZE 16G;

CREATE USER cdcdemo IDENTIFIED BY "passw0rd" DEFAULT TABLESPACE cdcdemo QUOTA UNLIMITED ON cdcdemo;

CREATE TABLE cdcdemo.tab0 (
  A INTEGER NOT NULL PRIMARY KEY,
  B VARCHAR2(100) NOT NULL
) TABLESPACE cdcdemo;

CREATE TABLE cdcdemo.tab1 (
  A INTEGER NOT NULL PRIMARY KEY,
  B VARCHAR2(100) NOT NULL
) TABLESPACE cdcdemo;

CREATE TABLE cdcdemo.tab2 (
  A INTEGER NOT NULL PRIMARY KEY,
  B VARCHAR2(100) NOT NULL
) TABLESPACE cdcdemo;

CREATE TABLE cdcdemo.tab3 (
  A INTEGER NOT NULL PRIMARY KEY,
  B VARCHAR2(100) NOT NULL
) TABLESPACE cdcdemo;

CREATE TABLE cdcdemo.tab4 (
  A INTEGER NOT NULL PRIMARY KEY,
  B VARCHAR2(100) NOT NULL
) TABLESPACE cdcdemo;

CREATE TABLE cdcdemo.tab5 (
  A INTEGER NOT NULL PRIMARY KEY,
  B VARCHAR2(100) NOT NULL
) TABLESPACE cdcdemo;

CREATE TABLE cdcdemo.tab6 (
  A INTEGER NOT NULL PRIMARY KEY,
  B VARCHAR2(100) NOT NULL
) TABLESPACE cdcdemo;

CREATE TABLE cdcdemo.tab7 (
  A INTEGER NOT NULL PRIMARY KEY,
  B VARCHAR2(100) NOT NULL
) TABLESPACE cdcdemo;

CREATE TABLE cdcdemo.tab8 (
  A INTEGER NOT NULL PRIMARY KEY,
  B VARCHAR2(100) NOT NULL
) TABLESPACE cdcdemo;

CREATE TABLE cdcdemo.tab9 (
  A INTEGER NOT NULL PRIMARY KEY,
  B VARCHAR2(100) NOT NULL
) TABLESPACE cdcdemo;
